spring:
  application:
    name: cloud-config-service
  cloud:
    inetutils:
      preferred-networks: 206.35.199
    config:
      label: master
      server:
        git:
          uri: https://github.com/intxzt/spring-cloud-netflix-config.git
          search-paths: repo
          username:
          password:
# 本地
#  profiles:
#    active: native #Comma-separated list of active profiles. Can be overridden by a command line switch.
#  cloud:
#    config:
#      server:
#        native:
#          search-locations: classpath:/config

server:
  port: 8888

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always