spring:
  application:
    name: spring-cloud-zuul

server:
  port: 8769

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
  routes:
    api-admin:
      path: /admin/**
      serviceId: cloud-admin-client